[package]
name = "pumpfun-pumpswap-copytrader"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
chrono = "0.4.26"
clap = { version = "4.5.7", features = ["derive"] }
anyhow = "1.0.62"
serde = "1.0.145"
serde_json = "1.0.86"
tokio = { version = "1.21.2", features = ["full"] }
tokio-tungstenite = { version = "0.23.1", features = ["native-tls"] }
tokio-stream = "0.1.11"
anchor-lang = "=0.30.1"
anchor-client = { version = "0.30.1", features = ["async"] }
yellowstone-grpc-client = "=1.15.4"
yellowstone-grpc-proto = "=1.14.2"
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }
spl-token-2022 = { version = "0.9.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "2.2.0", features = [
    "no-entrypoint",
] }
spl-token-client = "=0.7.1"
base64 = "0.22.1"
rand = "0.8.5"
borsh = { version = "1.5.3"}
borsh-derive = "1.5.3"
solana_trade_sdk = "0.1.0"
colored = "3.0.0"
reqwest = { version = "0.11.27", features = ["json", "socks", "native-tls"] }
lazy_static = "1.5.0"
bs58 = "0.4"
bs64 = "0.1.2"
bincode = "1.3.3"
tokio-js-set-interval = "1.3.0"
bytemuck = "1.21.0"
indicatif = "0.17.8"
tracing = "0.1.40"
futures-util = "0.3.30"
maplit = "1.0.2"
futures = "0.3.31"
solana-program = "1.18.11"